---
apiVersion: v1
kind: Pod
metadata:
  name: demo-printenv
spec:
  containers:
    - name: demo-printenv
      args:
        - while true; do echo -en '=====\n'; printenv; sleep 10; done;
      command:
        - sh
        - -c
      image: busybox
      env:
        - name: DEMO_ENV_VAR1
          valueFrom: 
            secretKeyRef:
              name: kube-simple-secret
              key: demo_env_var1_value
        - name: DEMO_ENV_VAR2
          valueFrom:
            secretKeyRef:
              name: kube-simple-secret
              key: demo_env_var2_value

