---
- hosts: localhost
  gather_facts: false

  tasks:

    - name: 'Example 1'
      ansible.builtin.command: ls -al
      changed_when: false

    - name: 'Example 2'
      ansible.builtin.set_fact:
        is_true: "{{ 2 | random }} == 1"
      changed_when: is_true

      # For Ansible version >=2.12 use:
      # changed_when: is_true | bool
