---
apiVersion: v1
kind: Service
metadata:
  name: training-app
  namespace: training
spec:
  type: LoadBalancer
  selector:
    app: training-app
  ports:
  - name: http
    port: 80
    targetPort: 3000
