apiVersion: v1
kind: Service
metadata:
  name: sample-kube-service
spec:
  type: NodePort
  selector:
    app: sample-kube-service
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30303
