apiVersion: v1
kind: Service
metadata:
  name: sample-kube-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: sample-kube-service
  ports:
  - name: http
    port: 80
    targetPort: 8080
