apiVersion: v1
kind: Service
metadata:
  name: exercise-app-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: exercise-app-service
  ports:
  - name: http
    port: 8081
    targetPort: 8080
