---
apiVersion: v1
kind: Service
metadata:
  name: training-db
  namespace: training
spec:
  type: ClusterIP
  selector:
    app: training-db
  ports:
  - name: db
    protocol: TCP
    port: 5432
    targetPort: 5432
