---
apiVersion: v1
kind: Service
metadata:
  name: training-db
  namespace: training
spec:
  selector:
    app: training-db
  ports:
  - name: db
    protocol: TCP
    port: 5432
    targetPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: training-db-external-ip
  namespace: training
spec:
  selector:
    app: training-db
  ports:
  - name: db
    protocol: TCP
    port: 5432
    targetPort: 5432
  externalIPs:
    - 192.168.49.2
