Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.ssh.insert_key = false
  config.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key", "vagrant_id_rsa"]

  config.vm.provision "file", source: "vagrant_id_rsa.pub", destination: "~/.ssh/authorized_keys"
  config.vm.provision "shell", inline: "sudo mkdir -p '/root/.ssh'"
  config.vm.provision "shell", inline: "sudo cp '/home/vagrant/.ssh/authorized_keys' '/root/.ssh/authorized_keys'"


  config.vm.provider :virtualbox do |v|
    v.memory = 512
  end

  config.vm.define "dev01" do |dev|
    dev.vm.hostname = "dev01"
    dev.vm.network :private_network, ip: "192.168.200.10"
  end

  config.vm.define "dev02" do |dev|
    dev.vm.hostname = "dev02"
    dev.vm.network :private_network, ip: "192.168.200.11"
  end

  config.vm.define "app01" do |app|
    app.vm.hostname = "app01"
    app.vm.network :private_network, ip: "192.168.200.101"
  end

  config.vm.define "app02" do |app|
    app.vm.hostname = "app02"
    app.vm.network :private_network, ip: "192.168.200.102"
  end

  config.vm.define "app03" do |app|
    app.vm.hostname = "app03"
    app.vm.network :private_network, ip: "192.168.200.103"
  end

  config.vm.define "db" do |db|
    db.vm.hostname = "db"
    db.vm.network :private_network, ip: "192.168.200.200"
  end

end
