---
- hosts: app
  gather_facts: yes
  tasks:
    - name: Clean up
      shell: |
        oldimage=`docker images | grep '<none>' | awk '{print $3}'`
        if [ -z "$oldimage" ]
        then
        echo "There is no dangling images found!"
        else
        docker rmi ${oldimage} -f
        fi
      ignore_errors: yes
      become: true
