---
apiVersion: v1
kind: Pod
metadata:
  name: demo-printenv
spec:
  containers:
    - name: demo-printenv
      args:
        - while true; do echo -en '\n'; cat /etc/demo/config/demo_env_var1_value; sleep 10; done;
      command:
        - sh
        - -c
      image: busybox
      volumeMounts:
        - name: demo-secret
          mountPath: "/etc/demo/config"
  volumes:
    - name: demo-secret
      secret:
        secretName: kube-simple-secret
